### PR TITLE
Proper error after biometric failure

### LINKED ISSUE #48: Wrong error message when using biometry
When I fail touch ID three times the following message is displayed:

image

### PR DESCRIPTION
**Pull request by kober32**
Fixed #48

### CODE REVIEW

File: Source/UI/Authentication/Process/AuthenticationModels.swift [hunk 1]
```diff
@@ -50,10 +50,12 @@ public enum Authentication {
         }
         
         public struct CommonErrors {
-			public let wrongPin: String
-			public let wrongPassword: String
+            public let wrongPin: String
+            public let wrongPassword: String
+            public let biometryNotRecognized_TouchId: String
+            public let biometryNotRecognized_FaceId: String
 			public let activationWasRemoved: String
```
Comment (hvge) [inline Source/UI/Authentication/Process/AuthenticationModels.swift]: Just fix also this remaining tabs :D That's due to my Xcode, which randomly selects tabs or spaces when I'm indenting the code :)

Comment (kober32) [reply Source/UI/Authentication/Process/AuthenticationModels.swift]: Fixed :)

**Comment by petrdvorak** [comment]
Messy tabs fixed, change looks OK.
